package de.tomalbrc.toms_mobs.entity.passive;
import de.tomalbrc.bil.api.AnimatedEntity; import de.tomalbrc.bil.core.holder.entity.EntityHolder; import de.tomalbrc.bil.core.holder.entity.living.LivingEntityHolder; import de.tomalbrc.bil.core.model.Model; import de.tomalbrc.toms_mobs.util.AnimationHelper; import de.tomalbrc.toms_mobs.util.Util; import eu.pb4.polymer.virtualentity.api.attachment.EntityAttachment;
import net.minecraft.resources.Identifier; import net.minecraft.server.level.ServerLevel; import net.minecraft.sounds.SoundEvent; import net.minecraft.sounds.SoundEvents; import net.minecraft.world.damagesource.DamageSource; import net.minecraft.world.entity.AgeableMob; import net.minecraft.world.entity.EntityType; import net.minecraft.world.entity.ai.attributes.AttributeSupplier; import net.minecraft.world.entity.ai.attributes.Attributes; import net.minecraft.world.entity.ai.goal.*; import net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal; import net.minecraft.world.entity.ai.navigation.PathNavigation; import net.minecraft.world.entity.animal.Animal; import net.minecraft.world.entity.animal.rabbit.Rabbit; import net.minecraft.world.entity.monster.Silverfish; import net.minecraft.world.entity.player.Player; import net.minecraft.world.item.ItemStack; import net.minecraft.world.item.Items; import net.minecraft.world.level.Level;
import net.tslat.smartbrainlib.api.core.navigation.SmoothGroundNavigation; import org.jetbrains.annotations.NotNull; import org.jetbrains.annotations.Nullable;
public class FennecFox extends Animal implements AnimatedEntity {
    public static final Identifier ID = Util.id("fennec_fox"); public static final Model MODEL = Util.loadBbModel(ID);
    private final EntityHolder<FennecFox> holder;
    @NotNull public static AttributeSupplier.Builder createAttributes() { return Animal.createMobAttributes().add(Attributes.MAX_HEALTH, 10.0).add(Attributes.MOVEMENT_SPEED, 0.3).add(Attributes.ATTACK_DAMAGE, 2.0); }
    @Override public EntityHolder<FennecFox> getHolder() { return this.holder; }
    public FennecFox(EntityType<? extends @NotNull Animal> type, Level level) { super(type, level); this.holder = new LivingEntityHolder<>(this, MODEL); EntityAttachment.ofTicking(this.holder, this); }
    @Override protected void registerGoals() { this.goalSelector.addGoal(0, new FloatGoal(this)); this.goalSelector.addGoal(2, new MeleeAttackGoal(this, 1.2, true)); this.goalSelector.addGoal(4, new WaterAvoidingRandomStrollGoal(this, 0.8)); this.goalSelector.addGoal(5, new RandomLookAroundGoal(this)); this.goalSelector.addGoal(6, new LookAtPlayerGoal(this, Player.class, 6.0F)); this.targetSelector.addGoal(1, new NearestAttackableTargetGoal<>(this, Rabbit.class, true)); this.targetSelector.addGoal(2, new NearestAttackableTargetGoal<>(this, Silverfish.class, true)); }
    @Override public void tick() { super.tick(); if (this.tickCount % 2 == 0) { AnimationHelper.updateWalkAnimation(this, this.holder); AnimationHelper.updateHurtColor(this, this.holder); } }
    @Override public boolean isFood(ItemStack i) { return i.is(Items.CHICKEN) || i.is(Items.RABBIT); }
    @Nullable @Override public AgeableMob getBreedOffspring(@NotNull ServerLevel l, @NotNull AgeableMob m) { return null; }
    @Override protected void dropCustomDeathLoot(@NotNull ServerLevel l, @NotNull DamageSource s, boolean r) { super.dropCustomDeathLoot(l, s, r); if (this.random.nextBoolean()) this.spawnAtLocation(l, new ItemStack(Items.RABBIT_HIDE, 1)); }
    @Override protected SoundEvent getHurtSound(@NotNull DamageSource d) { return SoundEvents.FOX_HURT; }
    @Override protected SoundEvent getDeathSound() { return SoundEvents.FOX_DEATH; }
    @Override protected @NotNull PathNavigation createNavigation(@NotNull Level l) { return new SmoothGroundNavigation(this, l); }
}
